master:
  image: spark-test
  command: bin/spark-class org.apache.spark.deploy.master.Master -h master
  hostname: master
  container_name: spark-master
  environment:
    MASTER: spark://master:7077
    SPARK_CONF_DIR: /conf
    SPARK_PUBLIC_DNS: localhost
  expose:
    - 7001
    - 7002
    - 7003
    - 7004
    - 7005
    - 7006
    - 7077
    - 6066
  ports:
    - 4040:4040
    - 6066:6066
    - 7077:7077
    - 8080:8080
  volumes:
    - ./conf/master/:/conf
    - ./data/:/data
    - ./:/workspace
  volumes_from:
    - logfiles

worker:
  image: spark-test
  command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://master:7077
  hostname: worker
  container_name: spark-worker-1
  environment:
    SPARK_CONF_DIR: /conf
    SPARK_WORKER_CORES: 1
    PARK_WORKER_INSTANCES: 1
    SPARK_WORKER_PORT: 8091
    SPARK_WORKER_WEBUI_PORT: 8092
    SPARK_PUBLIC_DNS: localhost
  links:
    - master
  expose:
  - 8091
  - 8092
  ports:
    - 8091:8091
    - 8092:8092
  volumes:
    - ./conf/worker/:/conf
    - ./data/:/data
    - ./:/workspace
  volumes_from:
    - logfiles

worker2:
  image: spark-test
  command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://master:7077
  hostname: worker
  container_name: spark-worker-2
  environment:
    SPARK_CONF_DIR: /conf
    SPARK_WORKER_CORES: 1
    SPARK_WORKER_INSTANCES: 1
    SPARK_WORKER_PORT: 8093
    SPARK_WORKER_WEBUI_PORT: 8094
    SPARK_PUBLIC_DNS: localhost
  links:
    - master
  expose:
  - 8093
  - 8094
  ports:
    - 8093:8093
    - 8094:8094
  volumes:
    - ./conf/worker/:/conf
    - ./data/:/data
    - ./:/workspace
  volumes_from:
    - logfiles

history:
  image: spark-test
  command: bin/spark-class org.apache.spark.deploy.history.HistoryServer
  hostname: history
  environment:
    SPARK_CONF_DIR: /conf
  expose:
    - 18080
  ports:
    - 18080:18080
  volumes:
    - ./conf/history:/conf
  volumes_from:
    - logfiles

logfiles:
  image: ubuntu:14.04
  volumes:
    - /tmp/spark-events